# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Build and deploy pages

on:
  push:
    branches: [ main ]
    paths-ignore:
    - README.md
    - .gitignore
    - _config.dev.yml
    - 'bin/**'
    - 'scaffolds/**'
    - 'workflows/**'
    - 'source/_drafts/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: alwaysdata
      url: https://thom4.net
    steps:
    # Setup
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
    - run: npm ci

    # Build
    - run: npm run build
      env:
        NODE_ENV: production

    # Deploy
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: "${{ secrets.SSH_DEPLOY_KEY }}"
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
    - run: npm run deploy

    # Index
    - name: Index content on Algolia
      run: npm run index-content
      env:
        HEXO_ALGOLIA_INDEXING_KEY: "${{ secrets.HEXO_ALGOLIA_INDEXING_KEY }}"
