# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Build and deploy pages

on:
  push:
    branches: [ main ]
    paths-ignore:
    - README.md
    - .gitignore
    - _config.dev.yml
    - 'bin/**'
    - 'scaffolds/**'
    - 'workflows/**'
    - 'source/_drafts/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Setup
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
    - run: npm ci

    # Build
    - run: npm run build
      env:
        NODE_ENV: production

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: production
      url: https://thom4.net
    steps:
    - name: Install mc
      run: |
        wget https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
    - name: Setup mc
      run: ./mc alias deuxfleurs https://garage.deuxfleurs.fr "${{ secrets.MINIO_ACCESS_KEY_ID }}" "${{ secrets.MINIO_SECRET_ACCESS_KEY }}" --api S3v4
    - name: Transfer
      run: ./mc mirror --overwrite --delete --exclude 'talks/*' --exclude 'photography/*' ./public/ deuxfleurs/thom4.net/

  index:
    runs-on: ubuntu-latest
    needs: [build]
    environment: alwaysdata
    steps:
    - name: Index content on Algolia
      run: npm run index-content
      env:
        HEXO_ALGOLIA_INDEXING_KEY: "${{ secrets.HEXO_ALGOLIA_INDEXING_KEY }}"
